//
//  NJHReporter.m
//  nettdating
//
//  Created by Nikolai Johan Heum on 24.05.15.
//  Copyright (c) 2015 Abello. All rights reserved.
//

// Helpers
#import "NJHReporter.h"
#import "NJHImgurAPIClient.h"
#import "NJHGithubAPIClient.h"

// View Controllers
#import "NJHReporterViewController.h"

// Categories
#import "UIWindow+NJH_ShakeNotifier.h"

@interface NJHReporter ()

@property (nonatomic, weak) NJHReporterViewController *reporterViewController;
@property (nonatomic) UIImage *autogeneratedScreenshot;

@end

@implementation NJHReporter

+ (instancetype)reporter {
    static NJHReporter *_sharedInstance;
    static dispatch_once_t onceToken;
    
    dispatch_once(&onceToken, ^{
        _sharedInstance = [[self alloc] init];
        _sharedInstance.enabled = YES;
    });
    
    return _sharedInstance;
}

+ (NSDateFormatter *)dateFormatter {
    static dispatch_once_t onceMark;
    static NSDateFormatter *formatter = nil;
    
    dispatch_once(&onceMark, ^{
        formatter = [NSDateFormatter new];
        [formatter setTimeZone:[NSTimeZone timeZoneWithName:@"UTC"]];
        [formatter setDateFormat:@"yyyy-MM-dd'T'HH:mm:ss.SSSSSS"];
    });
    
    return formatter;
}

+ (void)setupWithRepositoryName:(NSString *)reponame gitHubAccessToken:(NSString *)githubAccessToken {
    [self setupWithRepositoryName:reponame gitHubAccessToken:githubAccessToken imgurClientID:nil];
}

+ (void)setupWithRepositoryName:(NSString *)reponame gitHubAccessToken:(NSString *)githubAccessToken imgurClientID:(NSString *)imgurAccessToken {
    [NJHGithubAPIClient sharedClient].repositoryName = reponame;
    [[NJHGithubAPIClient sharedClient] setGithubAPIKey:githubAccessToken];
    [[NJHImgurAPIClient sharedClient] setImgurAPIKey:imgurAccessToken];
    
    [self reporter]; // Trigger the creation of the reporter object
}

- (instancetype)init {
    if (self = [super init]) {
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(showReporterView) name:kNJHSHakeNotificationName object:nil];
    }
    
    return self;
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self forKeyPath:kNJHSHakeNotificationName];
}

- (void)showReporterView {
    if (self.reporterViewController) { // Do not present if we are already on screen
        return;
    }
    
    if (!self.isEnabled) {
        return;
    }
    
    NJHReporterViewController *reporterController = [NJHReporterViewController instanceWithScreenshot:[self screenshot]];
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:reporterController];
    self.reporterViewController = reporterController;
    
    UIWindow *window = [[[UIApplication sharedApplication] delegate] window];
    [self presentReportComposer:navigationController inViewController:[window rootViewController]];
}

/**
 *  Present the report composer on the very topmost view controller as a modal presentation
 *
 *  @param composerController The controller to present
 *  @param rootViewController The canidate that we might present on
 */
- (void)presentReportComposer:(UIViewController *)composerController inViewController:(UIViewController *)rootViewController {
    if (rootViewController.presentedViewController) {
        [self presentReportComposer:composerController inViewController:rootViewController.presentedViewController];
    } else {
        [rootViewController presentViewController:composerController animated:YES completion:nil];
    }
}

- (void)uploadImageData:(NSData *)imageData completion:(void (^)(NSData *, NSString *))completionBlock error:(void (^)(NSError *, NSData *))errorBlock {
    [[NJHImgurAPIClient sharedClient] uploadImageData:imageData success:^(NSString *imageURL) {
        completionBlock(imageData, imageURL);
    } error:^(NSError *error) {
        errorBlock(error, imageData);
    }];
}

- (NSMutableDictionary *)extraInfoForIssue {
    NSMutableDictionary *extraInfo = [@{@"App Version : " : [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleShortVersionString"],
                                        @"Bundle Version : " : [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleVersion"],
                                        @"Current Localization : " : [NSLocale preferredLanguages][0],
                                        @"Current Device : " : [[UIDevice currentDevice] model],
                                        @"iOS Version : " : [[UIDevice currentDevice] systemVersion]} mutableCopy];
    
    [extraInfo addEntriesFromDictionary:[self.delegate extraDebuggingInformationForIssue]];
    return extraInfo;
}

- (UIImage *)screenshot {
    UIWindow *window = [[[UIApplication sharedApplication] delegate] window];
    
    UIGraphicsBeginImageContextWithOptions(window.bounds.size, NO, [UIScreen mainScreen].scale);
    [window.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    
    UIGraphicsEndImageContext();
    return image;
}

@end
