//
//  NJHReporterViewController.h
//  IssueReporter
//
//  Created by Nikolai Johan Heum on 04.05.15.
//  Copyright (c) 2015 Abello. All rights reserved.
//

#import "NJHImageCollectionViewController.h"

@import Foundation;
@import UIKit;

@interface NJHReporterViewController : UIViewController <NJHImageCollectionViewControllerDelegate>

+ (instancetype)instanceWithScreenshot:(UIImage *)image;

@property (nonatomic) UIImage *autogeneratedImage;

@end